services:
  # ==========================================
  # Backend Service (Spring Boot)
  # ==========================================
  backend:
    build:
      context: ./BackEnd/PodcastProject
      dockerfile: Dockerfile
    container_name: podcast_backend
    environment:
      # Apuntamos a la base de datos de Felipe a través de Radmin VPN
      - SPRING_DATASOURCE_URL=jdbc:mysql://26.30.81.16:3307/podcastutn?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8080:8080"
    networks:
      - podcast_app_network

  # ==========================================
  # Frontend Service (Angular + Nginx)
  # ==========================================
  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    container_name: podcast_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - podcast_app_network

networks:
  podcast_app_network:
    driver: bridge
